#!/usr/bin/env python
import os
import sys
import re

output = os.popen("git status -s").read()

lines = output.split('\n')

# Create index dirty patterns.
patterns = []
patterns.append(re.compile(" M .*"))
patterns.append(re.compile("A .*"))

# Gather dirty log lines
modifieds = []
for line in lines:
  for pattern in patterns:
    if re.match(pattern, line):
      modifieds.append(line)

# Abort once the index of working directory is dirty.
if len(modifieds):
  print "Aboring: checkout aborting if the working directory or the index is dirty."
  for line in modifieds:
    print line

  sys.exit(1)
else:
  params = ("" if len(sys.argv) == 0 else " ".join(sys.argv[1:]))
  os.system("git checkout " + params)

