#!/usr/bin/env python
import os
import sys
import re

output = os.popen("git status -s").read()

lines = output.split('\n')

# Create index dirty patterns.
patterns = []
patterns.append(re.compile(" M .*"))
patterns.append(re.compile("A .*"))

modifieds = []
for line in lines:
  for pattern in patterns:
    if re.match(pattern, line):
      modifieds.append(line)

if len(modifieds):
  print "Error: checkout abort if the working directory or the index is dirty."
  for line in modifieds:
    print line

  sys.exit(1)
else:
  # Concat argument(XXX: is there a easy way?)
  command = ''
  for i, line in enumerate(sys.argv):
    if i:
      command = command + " " + line

  os.system("git checkout " + command)

